name: Get latest release version
on:
  push:
    branches: master 
  #schedule:
   # - cron:  '6 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create a branch
        run: |
          git branch -d newbranch 
          git push origin :newbranch
          git checkout -b newbranch
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/POCorgself/maven-web-application/releases/latest | grep '"name":' |  sed -E 's/.*"([^"]+)".*/\1/' > release-versions/swagger-ui-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name 'Deepak'
          git config user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push origin newbranch
